spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?serverTimezone=UTC
    username: postgres
    password: 1111
  jpa:
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  flyway:
    enabled: true
    user: flyway
    password: flyway
    url: ${spring.datasource.url}
    baseline-on-migrate: true
    out-of-order: true
logging:
  level:
    org.springframework: INFO

listOfBills: 100,200,500
