spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/atm?serverTimezone=UTC
    username: postgres
    password: 1111
  jpa:
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
logging:
  level:
    org.springframework: INFO
